org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_version=4.1.1-1.21.1

mod_id=bots_lib
mod_name=Bots Lib

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_authors=coolbot100s,Chakyl
mod_group_id=cool.bot
mod_license=CC-BY-NC-SA-4.0
mod_description=Library with shared resources for my other mods. Exists mostly because I don't know what I'm doing.
